package repository

import (
	"testing"
	"time"

	"github.com/google/uuid"
)

func TestChannelBeforeCreateHook(t *testing.T) {
	ch := &Channel{Name: "test-ch", CreatedBy: "u1"}
	if err := ch.BeforeCreate(nil); err != nil {
		t.Fatalf("BeforeCreate failed: %v", err)
	}
	if ch.ID == "" {
		t.Error("expected ID to be generated by BeforeCreate hook")
	}
	if _, err := uuid.Parse(ch.ID); err != nil {
		t.Errorf("invalid UUID generated: %s", ch.ID)
	}
}

func TestMessageBeforeCreateHook(t *testing.T) {
	msg := &Message{ChannelID: "ch1", UserID: "u1", Username: "user1", Content: "hello"}
	if err := msg.BeforeCreate(nil); err != nil {
		t.Fatalf("BeforeCreate failed: %v", err)
	}
	if msg.ID == "" {
		t.Error("expected ID to be generated by BeforeCreate hook")
	}
	if _, err := uuid.Parse(msg.ID); err != nil {
		t.Errorf("invalid UUID generated: %s", msg.ID)
	}
}

func TestMessageUpdatedAtFieldExists(t *testing.T) {
	now := time.Now()
	msg := &Message{UpdatedAt: now}
	if msg.UpdatedAt.IsZero() {
		t.Error("expected UpdatedAt field to exist and be populated")
	}
}
