package repository

import (
	"testing"
	"time"

	"github.com/google/uuid"
)

func TestUserRoleConstants(t *testing.T) {
	if RoleSuperAdmin != "super_admin" {
		t.Errorf("expected super_admin, got %s", RoleSuperAdmin)
	}
	if RoleAdmin != "admin" {
		t.Errorf("expected admin, got %s", RoleAdmin)
	}
	if RoleUser != "user" {
		t.Errorf("expected user, got %s", RoleUser)
	}
}

func TestUserBeforeCreateHook(t *testing.T) {
	u := &User{Username: "hookuser", PasswordHash: "hash"}
	if err := u.BeforeCreate(nil); err != nil {
		t.Fatalf("BeforeCreate failed: %v", err)
	}
	if u.ID == "" {
		t.Error("expected ID to be generated by BeforeCreate hook")
	}
	if _, err := uuid.Parse(u.ID); err != nil {
		t.Errorf("invalid UUID generated: %s", u.ID)
	}
}

func TestUserAuditTimestamps(t *testing.T) {
	now := time.Now()
	u := &User{CreatedAt: now, UpdatedAt: now}
	if u.CreatedAt.IsZero() || u.UpdatedAt.IsZero() {
		t.Error("expected CreatedAt and UpdatedAt to exist and be populated")
	}
}
